joint_states:
  name: 
    - world_joint
    - base_joint
    - chest_joint
    - neck_joint
    - cam_joint
    - shoulder_joint
    - elbow_joint
    - end_joint
  position:
    - 0    # Position of joint1
    - 1.5   # Position of joint2
    - 0
    - 0
    - 1
    - 1
    - 0
    - 0
